"use client";

import { Inter } from "next/font/google";
import "../../globals.css";
import Footer from "@/components/Footer";
import { ReactQueryProvider } from "@/app/ReactQueryprovider";
import { useRouter } from "next/navigation";
import Nav from "@/components/Nav";
import TransactionNav from "@/components/TransactionNav";


const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Transction",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();

  // useEffect(() => {
  //   const accessToken = sessionStorage.getItem("access_token");
  //   if (!accessToken) {
  //     router.push("/Auth/login");
  //   }
  // }, [router]);

  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="center-max-width">
            <div className="content-container">
              <Nav />
              <TransactionNav/>
              {children}
              <Footer />
            </div>
          </div>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
